In [1]:
# import libraries for data manipulation
import pandas as pd
import numpy as np

In [2]:
# read file - takes a few seconds. Please replace the path with the exact path on your machine.
provider_info = pd.read_excel('../Raw Data Sets/Marked ProviderInfo_Download_HCS Comments.xlsx')
xls_puf = pd.ExcelFile('../Raw Data Sets/Marked_SNF PUF - Provider Final 2016_HCS Clear Header.xlsx')
snf_puf = pd.read_excel(xls_puf, "Provider")
contract_info = pd.read_csv('../Raw Data Sets/Marked_CPSC_Contract_Info_2018_12.csv',encoding='ISO-8859-1')
enrolment_info = pd.read_csv('../Raw Data Sets/Marked_CPSC_Enrollment_Info_2018_12.csv')

In [3]:
# drop un-needed columns from all datasets

# the columns to be kept in provider_info
provider_info_columns = ['PROVNUM','PROVNAME','BEDCERT', 'RESTOT','INHOSP','OVERALL_RATING','STATE','COUNTY_NAME']
# keep the columns needed in provider_info
provider_info_col_needed = provider_info[provider_info_columns]

# the columns to be kept in snf_puf file
snf_puf_columns = ['Provider ID','Total SNF Medicare Payment Amount','Average Length of Stay (Days)','Average HCC Score']
# keep the columns needed in snf_puf
snf_puf_col_needed = snf_puf[snf_puf_columns]

# the columns to be kept in contract info
contract_info_columns = ['Contract ID','Organization Marketing Name']
# keep the columns needed in contract info
contract_info_col_needed = contract_info[contract_info_columns]

## State Selection ##
You can change the scope of states in the block below.<br>
Change line 12 to whichever states you need.

In [4]:
# Choose different companies
contract_info_col_needed = contract_info_col_needed[contract_info_col_needed['Organization Marketing Name'].str.lower()
                                                    =='highmark senior health company'].drop_duplicates(subset=['Contract ID', 'Organization Marketing Name'])
# contract_info_col_needed = contract_info_col_needed[contract_info_col_needed['Organization Marketing Name'].str.lower()
#                                                     =='upmc for life'].drop_duplicates(subset=['Contract ID', 'Organization Marketing Name'])

# the columns to be kept in enrolment info
enrolment_info_columns = ['Contract Number','Plan ID', 'State', 'County','Enrollment']
# keep the columns needed in enrolment info
enrolment_info_col_needed = enrolment_info[enrolment_info_columns]
# Choose states
enrolment_info_col_needed = enrolment_info_col_needed[(enrolment_info_col_needed['State'].str.lower() == 'pa')|
                                                     (enrolment_info_col_needed['State'].str.lower()=='wv')|
                                                      (enrolment_info_col_needed['State'].str.lower() =='de')]

In [5]:
#Join provider info and snf_puf tables
#Convert joining column types to strings
provider_info_col_needed['PROVNUM'] = provider_info_col_needed['PROVNUM'].astype(str)
snf_puf_col_needed['Provider ID'] = snf_puf_col_needed['Provider ID'].astype(str)
# joining tables
provider_data = pd.merge(provider_info_col_needed, snf_puf_col_needed, 
                         left_on ='PROVNUM',right_on = 'Provider ID')

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [6]:
#Join contract_info and enrolment_info columns
#Convert joining column types to strings
contract_info_col_needed['Contract ID'] = contract_info_col_needed['Contract ID'].astype(str)
enrolment_info_col_needed['Contract Number'] = enrolment_info_col_needed['Contract Number'].astype(str)
# joining tables
enrolment_data = pd.merge(contract_info_col_needed, enrolment_info_col_needed, left_on='Contract ID',
                         right_on = 'Contract Number')
#rename county and state columns
enrolment_data = enrolment_data.rename(columns={'County': 'COUNTY_NAME', 'State':'STATE'})

In [7]:
# Process enrolment data
enrolment_data['Enrollment'] = enrolment_data['Enrollment'].replace('*', 0)
enrolment_data['Enrollment'] = enrolment_data['Enrollment'].astype('int')
enrollment_by_county = enrolment_data.groupby(['STATE','COUNTY_NAME'])['Enrollment'].sum()
enrollment_by_county = pd.DataFrame(enrollment_by_county)
enrollment_by_county = enrollment_by_county.rename(columns = {'Enrollment': 'ENROLLMENT'}).reset_index()[['STATE', 'COUNTY_NAME','ENROLLMENT']]
enrollment_by_county

    STATE COUNTY_NAME  ENROLLMENT
0      DE        Kent           0
1      DE  New Castle          33
2      DE      Sussex          49
3      PA       Adams        1719
4      PA   Allegheny       16510
5      PA   Armstrong        1829
6      PA      Beaver        2531
7      PA     Bedford         634
8      PA       Berks        5206
9      PA       Blair        1736
10     PA    Bradford         729
11     PA       Bucks          98
12     PA      Butler        2932
13     PA     Cambria        1452
14     PA     Cameron          70
15     PA      Carbon         638
16     PA      Centre        5033
17     PA     Chester         121
18     PA     Clarion         390
19     PA  Clearfield         834
20     PA     Clinton         190
21     PA    Columbia         102
22     PA    Crawford         685
23     PA  Cumberland        4596
24     PA     Dauphin        5316
25     PA    Delaware          92
26     PA         Elk         284
27     PA        Erie        3749
28     PA     Fayette        1239
29     PA      Forest          98
..    ...         ...         ...
95     WV       Mason          33
96     WV    McDowell           0
97     WV      Mercer           0
98     WV     Mineral          74
99     WV       Mingo           0
100    WV  Monongalia          19
101    WV      Monroe           0
102    WV      Morgan           0
103    WV    Nicholas           0
104    WV        Ohio          71
105    WV   Pendleton           0
106    WV   Pleasants           0
107    WV  Pocahontas           0
108    WV     Preston           0
109    WV      Putnam          33
110    WV     Raleigh           0
111    WV    Randolph           0
112    WV     Ritchie           0
113    WV       Roane           0
114    WV     Summers           0
115    WV      Taylor           0
116    WV      Tucker           0
117    WV       Tyler          49
118    WV      Upshur           0
119    WV       Wayne         118
120    WV     Webster           0
121    WV      Wetzel          91
122    WV        Wirt           0
123    WV        Wood          71
124    WV     Wyoming           0

[125 rows x 3 columns]

In [ ]:
# Export to csv
enrollment_by_county.to_csv("../Raw Data Sets/enrollment_by_county.csv")

## State Selection ##

In [ ]:
# Choose the provider data from PA, DE, WV
provider_data = provider_data[provider_data['STATE'] in ['PA', 'DE', 'WV']]
provider_data

In [ ]:
# Export to csv
provider_data.to_csv("../Raw Data Sets/provider_data.csv")